name: github release and npm publish

on:
  push:

jobs:
  release:
    environment:
      name: release
    runs-on: ubuntu-latest
    steps:
      - name: test token and env var
        run: |
          echo "environment secret: ${{ github.event.repository.name }}"
      # echo "environment secret: ${{ secrets.TEST_TOKEN }}"
      # echo "environment variable: ${{ vars.ENVIRONMENT_NAME }}"
