name: github release and npm publish

on:
  push:
    branches:
      - feat/github-actions/test-ashwinkumar6
      # - feat/github-actions/test-${{ github.repository_owner }}

jobs:
  release:
    environment:
      name: release
    runs-on: ubuntu-latest
    steps:
      - name: test token and env var
        run: |
          echo feat/github-actions/test-${{ github.repository_owner }}
      # echo "environment secret: ${{ secrets.TEST_TOKEN }}"
      # echo "environment variable: ${{ vars.ENVIRONMENT_NAME }}"
