name: github release and npm publish

on:
  workflow_call:

jobs:
  release:
    environment:
      name: release
    runs-on: ubuntu-latest
    steps:
      - name: test token and env var
        run: |
          echo "environment secret: ${{ secrets.GENERAL_TOKEN }}"
          echo "environment variable: ${{ vars.GENERAL_ENVIRONMENT_NAME }}"
          echo "environment secret: ${{ secrets.TEST_TOKEN }}"
          echo "environment variable: ${{ vars.ENVIRONMENT_NAME }}"
