name: github workflow
on:
  push:
    branches:
      - "main"

jobs:
  e2e_test:
    environment: general
    secrets: inherit
    uses: ./.github/workflows/callable-release.yml

  e2e_test_pre:
    runs-on: ubuntu-latest
    environment: general
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: test token and env var
        run: |
          cat .github/workflows/callable-release.yml
          echo "environment secret: ${{ secrets.GENERAL_TOKEN }}"
          echo "environment variable: ${{ vars.GENERAL_ENVIRONMENT_NAME }}"
          echo "environment secret: ${{ secrets.TEST_TOKEN }}"
          echo "environment variable: ${{ vars.ENVIRONMENT_NAME }}"
      - name: release and publish
        uses: ashwinkumar6/lerna-poc/.github/workflows/callable-release.yml@main
