name: github release and npm publish
on:
  push:
    branches:
      - "main"
jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "environment secret: ${{ secrets.TEST_TOKEN }}"
          echo "environment variable: ${{ vars.ENVIRONMENT_NAME }}"
