name: github release and npm publish

on:
  push:
    branches:
      - "main"
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "environment secret: ${{ secrets.TEST_TOKEN }}"
          echo "environment variable: ${{ vars.ENVIRONMENT_NAME }}"
